[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # Variables de entorno para el sistema completo GlamBook
  GMAIL_APP_PASSWORD = "islj xbmx bpzl ocpt"
  BUSINESS_EMAIL = "jadermonsalve9@gmail.com"
  BUSINESS_PHONE = "+57 300 699 7396"
  BUSINESS_ADDRESS = "Medellín, Colombia"
  NODE_ENV = "production"

# Configuración de formularios
[form]
  # Configurar las notificaciones de formularios
  # Los formularios se enviarán al panel de administración de Netlify

# Headers para seguridad y CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Redirecciones para SPA routing - NO redirigir las APIs
[[redirects]]
  from = "/admin"
  to = "/admin"
  status = 200
  force = false

[[redirects]]
  from = "/login"
  to = "/login"
  status = 200
  force = false

# Redirecciones para páginas específicas solamente
[[redirects]]
  from = "/undefined"
  to = "/404.html"
  status = 404

# Redireccionar después del envío del formulario
[[redirects]]
  from = "/testimonios"
  to = "/gracias"
  status = 200
  force = false